substitutions:
  name: "ble-proxy-1"
  friendly_name: Bluetooth proxy 1

packages:
  base: !include common/base.yaml

esp32:
  board: seeed_xiao_esp32c3

bluetooth_proxy:
  active: false

esp32_ble_tracker:
  scan_parameters:
    active: false
    interval: 800ms
    window: 800ms
