substitutions:
  name: rf-bridge
  friendly_name: RF Bridge

packages:
  base: !include common/base.yaml
  rf-bridge: github://oake/rf-bridge/package.yaml

external_components:
  - source: github://anna-oake/esphome-quinetic
  - source: github://anna-oake/esphome-vauno

api:
  homeassistant_services: true

# this creates sub-devices to make it pretty in Home Assistant
esphome:
  devices:
    - id: quinetic_maeve
      name: "Quinetic Maeve"
    - id: quinetic_zoe
      name: "Quinetic Zoë"
    - id: quinetic_front_door
      name: "Quinetic Front door"

#
# Quinetic starts here
#

quinetic:
  cc1101_id: radio_2

binary_sensor:
  - platform: quinetic
    device_id: quinetic_maeve
    name: "Wall switch"
    address: 0x7F31
  - platform: quinetic
    device_id: quinetic_zoe
    name: "Wall switch"
    address: 0xA39C
  - platform: quinetic
    device_id: quinetic_front_door
    name: "Doorbell"
    address: 0xFF86

light:
  - platform: quinetic
    address: 0xB000EE85
    device_id: quinetic_maeve
    name: "Ceiling light"
    icon: mdi:ceiling-light
  - platform: quinetic
    address: 0xB000E331
    device_id: quinetic_zoe
    name: "Ceiling light"
    icon: mdi:ceiling-light

#
# RF Remote starts here
#

remote_receiver:
  id: radio_1_rx
  pin: ${radio_1_gdo2}
  on_rc_switch:
    - lambda: |-
        if ((x.code >> 8) != 0xE409)
          return;

        uint8_t key = x.code & 0xFF;
        if (key == 0x00 || key > 0x15 ||
            key == 0x02 || key == 0x0B || key == 0x14)
          return;

        uint8_t key_id = key
          - (key >= 0x02)
          - (key >= 0x0B)
          - (key >= 0x14);

        ESP_LOGI("rf_remote", "Received key 0x%02X -> button %u", key, key_id);

        esphome::api::CustomAPIDevice api;
        api.fire_homeassistant_event(
          "esphome.rf_remote_key_pressed",
          {{"key_id", std::to_string(key_id)}}
        );

debug:
  update_interval: 5s

text_sensor:
  - platform: debug
    reset_reason:
      name: "Reset Reason"

bluetooth_proxy:
  active: false

esp32_ble_tracker:
  scan_parameters:
    active: false
    interval: 800ms
    window: 800ms
