substitutions:
  name: usb-switch
  friendly_name: USB Switch

packages:
  base: !include common/base.yaml

esp8266:
  board: d1_mini

esphome:
  on_boot:
    then:
      - lambda: |-
          pinMode(D1, INPUT);
          id(active_input).publish_state(id(usb1_active).state ? "USB1" : "USB2");

binary_sensor:
  - platform: gpio
    id: usb1_active
    internal: true
    pin:
      number: D2
      inverted: true
    filters:
      - delayed_on_off: 10ms
    on_state:
      - lambda: |-
          id(active_input).publish_state(x ? "USB1" : "USB2");

button:
  - platform: template
    id: toggle_active_input
    name: Toggle Active Input
    icon: mdi:swap-vertical
    on_press:
      then:
        - lambda: |-
            pinMode(D1, OUTPUT);
            digitalWrite(D1, LOW);
        - delay: 50ms
        - lambda: |-
            pinMode(D1, INPUT);

select:
  - platform: template
    id: active_input
    name: Active Input
    icon: mdi:source-branch
    options:
      - USB1
      - USB2
    set_action:
      - lambda: |-
          auto current = id(usb1_active).state ? "USB1" : "USB2";
          if (x != current) {
            id(toggle_active_input).press();
          }
