substitutions:
  name: vfd-clock-sdl
  friendly_name: VFD Clock SDL

packages:
  host: !include common/host.yaml

font:
  - file: "fonts/hunter.ttf"
    id: f_hunter
    size: 9
    bpp: 1
  - file:
      url: "https://github.com/IdreesInc/Monocraft/releases/download/v3.0/Monocraft.ttf"
      type: web
    id: f_main
    size: 20
  - file: "fonts/vhs.ttf"
    id: f_vhs
    size: 34
  - file: "fonts/MatrixChunky8X.bdf"
    id: f_matrix
  - file: "fonts/UV.bdf"
    id: f_uv

time:
  - platform: homeassistant
    timezone: Europe/London
    id: tm

# sensor:
#   - platform: homeassistant
#     id: w_temp
#     entity_id: sensor.knmi_temperature
#     # entity_id: sensor.weather_home_temperature
#   - platform: homeassistant
#     id: w_high_temp
#     entity_id: knmi_max_temperature_today
#     # entity_id: sensor.weather_home_high_temperature
#   - platform: homeassistant
#     id: w_low_temp
#     entity_id: knmi_min_temperature_today
#     # entity_id: sensor.weather_home_low_temperature
#   # - platform: homeassistant
#   #   id: w_uv
#   #   entity_id: sensor.weather_home_uv_index

display:
  - platform: sdl
    id: vfd
    update_interval: 1s
    dimensions:
      width: 256
      height: 48
    lambda: |-
      auto now = id(tm).now();

      // big frame
      // it.rectangle(0, 0, 207, 48);
      // top bar
      // it.line(0, 10, 206, 10);

      // clock
      it.strftime(50, 28, id(f_main), TextAlign::CENTER, "%H:%M:%S", now);

      // calendar frame
      it.rectangle(208, 0, 48, 48);
      // calendar top bar
      it.filled_rectangle(208, 0, 48, 11);

      // calendar weekday
      std::string day = now.strftime("%a");
      for (int i = 0; i < day.length(); i++)
        day[i] = toupper(day[i]);
      it.print(232, 1, id(f_hunter), COLOR_OFF, TextAlign::TOP_CENTER, day.c_str());

      // calendar date
      it.strftime(233, 32, id(f_vhs), TextAlign::CENTER, "%d", now);

      // weather temperature
      it.printf(5, 1, id(f_matrix), "%.0f °C", 25.6f);

      // UV
      it.print(1, 0, id(f_uv), "# 0 1 2 3 4 5 6 7 8 9 !");
