esphome:
  name: ${name}
  friendly_name: ${friendly_name}

logger:

api:
  encryption:
    key: !secret api_key

ota:
  - platform: esphome
    password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: true # skips scanning, needed for hidden networks
  ap:
    ssid: ${friendly_name}
    password: !secret ap_password

captive_portal:

external_components:
  - source:
      type: local
      path: components
